server:
  port: 9001

spring:
  application:
    name: instance-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/

logging:
  path: ./log